# Generated by Django 2.2.13 on 2021-01-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_auto_20210126_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gabaritoaluno',
            name='questao',
        ),
    ]
