version: '2.4'
services:
  web:
    container_name: web-school
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    working_dir: /etc/nginx
    links:
      - python
  python:
    container_name: python-school
    build: ./docker/python
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: docker/mysql
    container_name: mysql-school
    ports:
      - 3306:3306
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=alf_school
    healthcheck:
      test: "exit 0"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    container_name: phpmyadmin-school
    environment:
      
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    volumes:
      - .docker/phpmyadmin/data/sessions:/sessions

volumes:
  data-volume:
